[package]
name = "sagitta-remote-system-workspace"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_cbor = { workspace = true }

sagitta-remote-system-db = { workspace = true }

[lints.clippy]
unwrap_used = { level = "deny" }
