[workspace]
resolver = "2"
members = [
    "sagitta",
    "sagitta-api-schema",
    "sagitta-common",
    "sagitta-integration-tests", 
    "sagitta-local-system-workspace", 
    "sagitta-local-user-workspace",
    "sagitta-objects",
    "sagitta-objects-store", 
    "sagitta-remote-system-archive", 
    "sagitta-remote-system-workspace",
    "sagitta-server",
]

[workspace.dependencies]
actix-web = { version = "4.5.1" }
brotli = "3.5.0"
clap = { version = "4.5.4", features = ["derive"] }
dotenvy = { version = "0.15.7" }
env_logger = "0.11.3"
fuser = { version = "0.14.0", features = ["serializable"] }
insta = "1.38.0"
libc = "0.2.154"
log = "0.4.21"
serde = { version = "1.0.201", features = ["derive"] }
serde_json = { version = "1.0.117" }
serde_cbor = "0.11.2"
serial_test = "3.1.1"
surrealdb = "1.4.2"
sha2 = "0.10.8"
tempfile = "3.10.1"
tokio = { version = "1.36.0", features = ["macros", "rt-multi-thread"] }
ureq = { version = "2.9.7", features = ["json"] }

sagitta = { path = "sagitta" }
sagitta-common = { path = "sagitta-common" }
sagitta-objects = { path = "sagitta-objects" }
sagitta-objects-store = { path = "sagitta-objects-store" }
sagitta-api-schema = { path = "sagitta-api-schema" }
sagitta-server = { path = "sagitta-server" }
sagitta-integration-tests = { path = "sagitta-integration-tests" }
sagitta-remote-system-workspace = { path = "sagitta-remote-system-workspace" }
sagitta-local-system-workspace = { path = "sagitta-local-system-workspace" }
