[package]
name = "sagitta-integration-tests"
version = "0.1.0"
edition = "2021"

[dependencies]
insta = { workspace = true }
sagitta = { workspace = true }
sagitta-api-schema = { workspace = true }
sagitta-objects = { workspace = true }
sagitta-server = { workspace = true }
serde_cbor = { workspace = true }
serial_test = { workspace = true }
ureq = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true }
