[package]
name = "sagitta"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = { workspace = true }
env_logger = { workspace = true }
fuser = { workspace = true }
insta = { workspace = true }
libc = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_cbor = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true }
ureq = { workspace = true }

sagitta-objects = { workspace = true }
sagitta-api-schema = { workspace = true }
sagitta-objects-store = { workspace = true }
